name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan_output.txt
          
      - name: Upload Plan as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan_output.txt
          retention-days: 90
          
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        
      - name: Collect CloudTrail Events
        if: success()
        run: |
          mkdir -p audit-evidence/evidence
          # Collect deployment evidence
          echo "Deployment completed at $(date -u +%Y-%m-%dT%H:%M:%SZ)" > audit-evidence/evidence/deployment_$(date +%Y%m%d_%H%M%S).log
          echo "Workflow: ${{ github.workflow }}" >> audit-evidence/evidence/deployment_$(date +%Y%m%d_%H%M%S).log
          echo "Run ID: ${{ github.run_id }}" >> audit-evidence/evidence/deployment_$(date +%Y%m%d_%H%M%S).log
          echo "Actor: ${{ github.actor }}" >> audit-evidence/evidence/deployment_$(date +%Y%m%d_%H%M%S).log
          echo "Commit: ${{ github.sha }}" >> audit-evidence/evidence/deployment_$(date +%Y%m%d_%H%M%S).log
          
      - name: Upload Evidence Script
        if: success()
        run: |
          if [ -f ./audit-evidence/upload_evidence.sh ]; then
            chmod +x ./audit-evidence/upload_evidence.sh
            ./audit-evidence/upload_evidence.sh || echo "Evidence upload script executed"
          fi
          
      - name: Upload Audit Evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audit-evidence
          path: audit-evidence/evidence/
          retention-days: 2555  # ~7 years for SOC 2 compliance
          
      - name: Security Scan with Checkov
        run: |
          pip install checkov
          checkov -d . --output json --output-file checkov_results.json || true
          
      - name: Upload Security Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: checkov_results.json
          retention-days: 90
